export const eventsData = [
  {
    id: 1,
    image: "https://www.apwa.org.au/images/womens-day-2025.jpg",
    link: "https://www.facebook.com/share/p/1ECJPg8SnT/?mibextid=wwXIfr",
    location: "Sydney",
    title: "International Women's Day",
    description: `The AusPak Women's Association (APWA), in collaboration with the
                Southern Cross Institute (SCI) and Australian Humanity Private
                Limited, and Co sponsored by Penrith City Counsil...`,
    date: "Mar.16.2025",
    time: "10:30AM - 3:30PM",
  },
  {
    id: 2,
    image: "https://www.apwa.org.au/images/pink-stump.jpg",
    link: "https://www.facebook.com/share/1EXAJeBGGQ/?mibextid=wwXIfr",
    location: "Blacktown",
    title: "Pink Stump Day",
    description: `Due to rain the venue for Pink Stump Day 2024 is changed to —
                Play point Blacktown 2A Bessemer St, Blacktown NSW 2148 Event
                will start at 11 am sharp.`,
    date: "Nov.30.2024",
    time: "11:00AM - 3:30PM",
  },
  {
    id: 3,
    image: "https://www.apwa.org.au/images/breast-cancer.jpg",
    link: "https://www.facebook.com/story.php?story_fbid=490933003932157&id=100090463843342&mibextid=WC7FNe&rdid=9y4kg1cIwBllRKR2#",

    location: "Sydney",
    title: "Breast Cancer Awareness",
    description: `The Southern Cross Institute and APWA hosted a momentous
                ceremony to celebrate the organization's second anniversary and
                Breast Cancer Awareness Day...`,
    date: "Oct.04.2024",
    time: "10:30AM - 3:30PM",
  },
  {
    id: 4,
    image: "https://www.apwa.org.au/images/fathers-day.jpg",
    link: "https://www.facebook.com/story.php?story_fbid=471123785913079&id=100090463843342&mibextid=WC7FNe&rdid=JBHWPCeG3PPj0Liu#",

    location: "Cottage Laal Qila",
    title: "Father's Day Celebration",
    description: `APWA hosted a wonderful Father's Day celebration at The Cottage by Laal Qila, a stunning venue that added to the joy of the day. Noureen did a great job hosting the event, which was filled with love, laughter, and fun.`,
    date: "Sep.08.2024",
    time: "10:30AM - 3:30PM",
  },
  {
    id: 5,
    image: "https://www.apwa.org.au/images/event-1.jpg",
    link: "https://www.facebook.com/share/r/145TghSwJZ/?mibextid=UalRPS",

    location: "Auburn",
    title: "Independence Day Celebration",
    description: `A colorful parade took place in the streets of Auburn on August 13th, 2024, to celebrate Pakistani Independence Day. The event was organized by APWA and saw enthusiastic participation from the local community.`,
    date: "Aug.14.2024",
    time: "10:30AM - 3:30PM",
  },
  {
    id: 6,
    image: "https://www.apwa.org.au/images/event-2.jpg",
    link: "https://www.facebook.com/share/r/1A8VmU6j2N/?mibextid=UalRPS",

    location: "Sydney",
    title: "Eid Gala & Fundraising Dinner",
    description: `The AusPak Woman Association organized a memorable Multicultural Eid Gala and Fundraising Dinner on 23rd June fostering a sense of unity and celebrating diverse cultures sense of unity and celebrating diverse cultures.`,
    date: "June.23.2024",
    time: "10:30AM - 3:30PM",
  },
  {
    id: 7,
    image: "https://www.apwa.org.au/images/event-3.jpg",
    link: "https://www.facebook.com/share/v/dspqcYwoC8pEXeKh/",

    location: "Sydney",
    title: "Special Screening & Umrao Ayyar",
    description: `The AusPak Woman Organisation proudly presented a special screening of "Umro Ayyar," a Pakistani film that has captivated audiences with its beautifully presented fictional action and revival of the classic Alif Laila sto...`,
    date: "June.14.2024",
    time: "10:30AM - 3:30PM",
  },
  {
    id: 8,
    image: "https://www.apwa.org.au/images/event-4.jpg",
    link: "https://www.facebook.com/share/v/PPrgSQBJj6h8aSEg/",

    location: "Sydney",
    title: "Mother's Day Celebration",
    description: `Aus Pak Woman Association, Australian Humanity Support limited and Community Migrant Resource Centre hosted a wonderful function to celebrate International Mother's Day, honoring the selfless love and dedication of mother...`,
    date: "May.11.2024",
    time: "10:30AM - 3:30PM",
  },
  {
    id: 9,
    image: "https://www.apwa.org.au/images/event-5.jpg",
    link: "https://www.facebook.com/reel/1100046311114406",

    location: "Sydney",
    title: "Friendship Festival",
    description: `Apwa's Friendship Festival Culminated In Triumph, Highlighting The Beauty Of Unity And Cultural Harmony. Attendees Were Enthralled By Diverse Performances, Fostering A Spirit Of Inclusivity And Mutual Respect.`,
    date: "April.07.2024",
    time: "10:30AM - 3:30PM",
  },
  {
    id: 10,
    image: "https://www.apwa.org.au/images/event-6.jpg",
    link: "https://www.facebook.com/share/r/14mhCozMLW/?mibextid=UalRPS",

    location: "Sydney",
    title: "International Women's Day",
    description: `A day dedicated to honoring the social, economic, cultural, and political achievements of women around the world. The purpose of this event is to raise awareness about gender equality, women's rights, and to celebrate the...`,
    date: "March.08.2024",
    time: "10:30AM - 3:30PM",
  },
  {
    id: 11,
    image: "https://www.apwa.org.au/images/event-7.jpg",
    link: "https://www.facebook.com/share/p/DaAL84qS4TM3ozen/?mibextid=WC7FNe",

    location: "Alfred",
    title: "X-Mas Eve Food Drive",
    description: `Another year of successful APWA Christmas food drive. Thanks for all our sponsors for participating & supporting this cause. Thanks for all our sponsors for participating & supporting this cause...`,
    date: "Dec.23.2023",
    time: "10:30AM - 3:30PM",
  },
  {
    id: 12,
    image: "https://www.apwa.org.au/images/event-8.jpg",
    link: "https://www.facebook.com/share/p/n58CWkYgyypAsoDV/",

    location: "Parramatta",
    title: "Interfaith Christmas Festival",
    description: `In Parramatta, a beautiful area of ​​Sydney, Australia, AUS PAK WOMEN'S ASSOCIATION decorated the INTERFAITH CHRISTMAS FESTIVAL in which people from different countries and religions participated and many cultural perfor...`,
    date: "Dec.09.2023",
    time: "10:30AM - 3:30PM",
  },
  {
    id: 13,
    image: "https://www.apwa.org.au/images/event-9.jpg",
    link: "https://youtu.be/7J38_uOX3k0?si=HfeXsFYMXoK5h35R",

    location: "Sydney",
    title: "Meri Awaz Suno",
    description: `AusPak Women association team works day and night towards fulfilment of one goal establishing a safe heaven for women and victims of domestic violence, APWA Nest.`,
    date: "Nov.25.2023",
    time: "10:30AM - 3:30PM",
  },
  {
    id: 14,
    image: "https://www.apwa.org.au/images/event-10.jpg",
    location: "Doonside Community Centre, Blacktown",
    title: "Eid Milad-un-Nabi",
    description: `Attended in massive strength by the ladies from the community and our very dear Councilor Kushpinder Kaur. The purpose of the Eid Milad-un-Nabi function was to commemorate...`,
    date: "Oct.08.2023",
    time: "10:30AM - 3:30PM",
  },
  {
    id: 15,
    image: "https://www.apwa.org.au/images/event-12.jpg",
    location: "Auburn Park",
    title: "APWA Biscuit Party",
    description: `APWA Biscuit party was organized to celebrate the launch of APWA KIDS WING on the 9th of September, 2023 at Auburn Park was a joyful celebration aimed at providing children...`,
    date: "Sep.09.2023",
    time: "10:30AM - 3:30PM",
  },
  {
    id: 16,
    image: "https://www.apwa.org.au/images/fathers-day.jpg",
    location: "Doonside Community Centre, Blacktown",
    title: "Father's Day Celebration",
    description: `Father’s Day Celebration took place on the 2nd Sept 2023 at Sizzlingo restaurant to honor and appreciate fathers and father figures for their love, guidance, and support...`,
    date: "Sep.02.2023",
    time: "10:30AM - 3:30PM",
  },
  {
    id: 17,
    image: "https://www.apwa.org.au/images/event-14.jpg",
    location: "Auburn",
    title: "APWA Azaadi Parade",
    description: `APWA Azadi Parade, organized on August 13, 2023, to celebrate Independence Day and foster a sense of unity and pride within the community of ...`,
    date: "Aug.13.2023",
    time: "10:30AM - 3:30PM",
  },
  {
    id: 18,
    image: "https://www.apwa.org.au/images/event-15.jpg",
    location: "Redgum Centre, Wentworthville",
    title: "Imam Hussain Peace Conference",
    description: `The Imam Hussain A.S Peace Conference, which began on July 19th, 2023, at the Redgum Centre in Wentworthville, aimed to promote peace, unity, and understanding...`,
    date: "July.19.2023",
    time: "10:30AM - 3:30PM",
  },
  {
    id: 19,
    image: "https://www.apwa.org.au/images/event-16.jpg",
    location: "Nepean River, Penrith",
    title: "APWA Eid Picnic",
    description: `APWA Eid Picnic, hosted on July 8th, 2023, at Nepean River, Penrith, was to celebrate Eid ul-Fitr with the community in a relaxed and picturesque setting. The event aimed to provide...`,
    date: "July.08.2023",
    time: "10:30AM - 3:30PM",
  },
  {
    id: 20,
    image: "https://www.apwa.org.au/images/event-17.jpg",
    link: "https://youtu.be/M5Jnie_Xj7w?si=z9LXTCZEuzWXPSD0",

    location: "Granville Centre",
    title: "Eid-ul-Adha Festival",
    description: `"Eid Before Eid" – Eid ul Azha Festival, held on June 25th, 2023, at Granville Centre, was to provide an early celebration for the upcoming Eid ul Azha festival. The event aimed to bring together...`,
    date: "July.25.2023",
    time: "10:30AM - 3:30PM",
  },
  {
    id: 21,
    image: "https://www.apwa.org.au/images/event-18.jpg",
    link: "https://www.youtube.com/watch?v=kvkp23R_LW8",

    location: "Doonside Neighborhood Centre",
    title: "Maa Tujhy Salaam",
    description: `APWA Mother’s Day Celebration "Maa Tujhey Salaam," held on May 13th, 2023, at Doonside Neighborhood Centre, was to honor and appreciate mothers for their love...`,
    date: "May.13.2023",
    time: "10:30AM - 3:30PM",
  },
  {
    id: 22,
    image: "https://www.apwa.org.au/images/event-19.jpg",
    location: "Hoyts Cinema, Blacktown",
    title: "Money Back Guarantee",
    description: `Showcasing of the Red Carpet of "Money Back Guarantee" during the Anzac Day Celebration on April 25th, 2023, at Hoyts Cinema, Blacktown, was to pay tribute to the Anzacs...`,
    date: "July.19.2023",
    time: "10:30AM - 3:30PM",
  },
  {
    id: 23,
    image: "https://www.apwa.org.au/images/event-20.jpg",
    link: "https://www.facebook.com/share/v/xJUH57Yinbdg8X4y/",

    location: "Granville Centre",
    title: "APWA Chand Raat Festival",
    description: `APWA Chand Raat Festival, held on April 20th, 2023, at Granville Centre, was to celebrate the eve of Eid-ul-Fitr, a significant religious festival in the Islamic calendar...`,
    date: "April.20.2023",
    time: "10:30AM - 3:30PM",
  },
  {
    id: 24,
    image: "https://www.apwa.org.au/images/event-21.jpg",
    link: "https://youtu.be/0nNyjv3SyWQ?si=O_AGkgYrHw1FNlOk",

    location: "Sydney",
    title: "Pakistan Day Celebration",
    description: `On March 24th, 2023, APWA hosted a Pakistan Day and Iftar dinner, graced by Excellency of High Commissioner of Pakistan, Mr. Zahid Hafeez Chaudhri...`,
    date: "March.24.2023",
    time: "10:30AM - 3:30PM",
  },
  {
    id: 25,
    image: "https://www.apwa.org.au/images/event-22.jpg",
    link: "https://youtu.be/9pO6GVHsj4Q?si=Rzxlul8YsSiC64XY",

    location: "El Amour Reception Lounge, Guildford",
    title: "International Women's Day",
    description: `On March 10th, 2023, APWA celebrated International Women's Day with the grand formal launch event held at El Amour Reception Lounge, Guildford...`,
    date: "March.10.2023",
    time: "10:30AM - 3:30PM",
  },
  {
    id: 26,
    image: "https://www.apwa.org.au/images/event-24.jpg",
    link: "https://youtu.be/4piznJAgKjw?si=2TuBooAG1Z-ZTc0d",

    location: "Centenary Square, Parramatta",
    title: "The Candlelight Vigil",
    description: `The Candlelight Vigil held on February 12, 2023, at Centenary Square Parramatta, was a solemn gathering in support of the innocent lives lost in Peshawar, Pakistan...`,
    date: "Feb.12.2023",
    time: "10:30AM - 3:30PM",
  },
  {
    id: 27,
    image: "https://www.apwa.org.au/images/event-25.jpg",
    link: "https://youtu.be/4piznJAgKjw?si=2TuBooAG1Z-ZTc0d",

    location: "Bankstone Senior Cenre",
    title: "Paint the Pain",
    description: `“Paint the Pain” an ART EXPO was organized in solidarity with the people of Occupied Kashmir was held on the 5th February, 2023 at Bankstown Senior Centre to raise awareness...`,
    date: "Feb.05.2023",
    time: "10:30AM - 3:30PM",
  },
  {
    id: 28,
    image: "https://www.apwa.org.au/images/event-26.jpg",
    link: "https://youtu.be/rJXVgQ6uVTE?si=-7Kn3IZk89KVjlrw",

    location: "Event Cinema, Parramatta",
    title: "APWA Movie Night",
    description: `APWA Movie Night, held on January 30, 2023, provided the community with an opportunity to come together for an enjoyable and culturally enriching experience...`,
    date: "Jan.30.2023",
    time: "10:30AM - 3:30PM",
  },
];
